### ISSUE TITLE
Suggestion about apc_common package

### ISSUE THREAD

**Issue by wkentaro** [amazon-picking-challenge/administration#10]
It is useful if there is a package which contains common stacks for the challenge.
like:
- gazebo model of kiva_pod and objects
- sample json files
- json file generator
- rviz visualization server (which is for audience and each team publish or request the robot state to it)

I have gazebo models in my project [repo](https://github.com/start-jsk/jsk_apc/tree/master/jsk_2015_apc_common/models). 

and this is firstly suggested at https://github.com/start-jsk/jsk_apc/issues/957.

cc: @k-okada @rethink-imcmahon

**Comment by dpsolomon** [comment]
I like this idea.  My initial thought is to create a repository with read/write access to all members of the [APC](https://github.com/amazon-picking-challenge) organization.  Under that repository could live a number of packages:
- apc_data2014
- apc_data2015
- etc.

or a flatter package layout (apc_data with directories for 2014/15).

**Comment by wkentaro** [comment]
I thought below directory construction.

```
apc_data
+ --- apc_data: Meta package
      + --- package.xml
      + --- CMakeLists.txt
+ --- apc_data2015: data for APC2015
      + --- package.xml
            + --- CMakeLists.txt
            + --- models
                  + --- kiva_pod: contains models.config, models.sdf and stl files
                  + --- oreo_mega_stuf
                  + ...
+ --- apc_data2016: data for APC2016
      + --- package.xml
      + --- CMakeLists.txt
      + --- ...
```

If we use `common` in the name not `data`, we can install not just data but scripts or nodes sample. (ex. apc_data -> apc_common, apc_data2015 -> apc_common2015)
Also I wonder which one is better `apc_XXX2015` or `apc2015_XXX`.

**Comment by rethink-imcmahon** [comment]
+1 for the `common` package name designation. It's pretty ubiquitous throughout ROS package naming. I also like either `apc2015_common` or `apc_2015_common` with a `apc_common` parent directory:

```
apc_common:
+ --- apc_common: Meta package
      + --- package.xml
      + --- CMakeLists.txt
+ --- apc_2015_common: resources for APC2015
      + --- package.xml
      + --- CMakeLists.txt
      + --- models/
              + --- kiva_pod/ contains models.config, models.sdf and stl files
              + --- oreo_mega_stuff/
              + ...
+ --- apc_2016_common: resources for APC2016
      + --- package.xml
      + --- CMakeLists.txt
      + --- ...
```

**Comment by dpsolomon** [comment]
Really sorry that I haven't been able to pay too much attention to this issue - had a family emergency that was disrupting the normal flow.

In either case, I created the apc_common repository, but I am trying to figure out how to manage access.  The easiest approach for me is to give everyone in the organization write access, but I'm afraid that would make it a bit a wild frontier.

The 2nd easiest would be a team of 'team maintainers' that have write access, which feels like it would be slightly more controlled.

The 3rd option, and the one I am currently pursuing, is to create a team from the members who are interested in contributing to this repository (i.e. the participants of this conversation) that will have write access.

Please comment and let me know your thoughts. I'll leave the issue open for a while until we reach some sort of resolution.

**Comment by k-okada** [comment]
I would propose 4th option that current manager of this repository keep
write access and control this package. And all teams contributing thorough
PR. This may require a lot of effort on managers, but teams are able to
focus on thieir work and hopefully this makes APC more interesting.

2015年12月1日火曜日、Daniel Solomonnotifications@github.comさんは書きました:

> Really sorry that I haven't been able to pay too much attention to this
> issue - had a family emergency that was disrupting the normal flow.
> 
> In either case, I created the apc_common repository, but I am trying to
> figure out how to manage access. The easiest approach for me is to give
> everyone in the organization write access, but I'm afraid that would make
> it a bit a wild frontier.
> 
> The 2nd easiest would be a team of 'team maintainers' that have write
> access, which feels like it would be slightly more controlled.
> 
> The 3rd option, and the one I am currently pursuing, is to create a team
> from the members who are interested in contributing to this repository
> (i.e. the participants of this conversation) that will have write access.
> 
> Please comment and let me know your thoughts. I'll leave the issue open
> for a while until we reach some sort of resolution.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/amazon-picking-challenge/administration/issues/10#issuecomment-160786582
> .

## 

## 

◉ Kei Okada

**Comment by wkentaro** [comment]
I agree with @k-okada 's idea, and when you find other collaborators, you can give them the write access right.

**Comment by dpsolomon** [comment]
I'm on board with having a small number of managers for this repository, I just don't think I can be one of them.

I'll put a note on [apc_common/README.md](https://github.com/amazon-picking-challenge/apc_common/blob/master/README.md) that interested parties should apply to be a manager. Then, hopefully, there will soon be enough managers to handle pull requests, etc.

@k-okada, would you like to be one of the managers?
