### ISSUE TITLE
Joint APC 2016

### ISSUE THREAD

**Issue by rojas70** [amazon-picking-challenge/administration#11]
Username:    rojas70
Team Name: 2016BIRLAPC

**Comment by dpsolomon** [comment]
@rojas70 ,
Sorry for the late response. I have been leaving date information out of the repository name, and letting teams have a directory or a branch inside their repository that separates by year.

Is it OK if I name your repository BIRLAPC?

Thanks,
Dan

**Comment by rojas70** [comment]
Yes. No prob
