### ISSUE TITLE
Team CVAP maintainer

### ISSUE THREAD

**Issue by dpsolomon** [amazon-picking-challenge/administration#13]
@fevb, would you like to be the team maintainer for the CVAP APC repository?

**Comment by fevb** [comment]
yes, that sounds good

**Comment by dpsolomon** [comment]
Invitation sent. When accepted, please update this issue to make sure I get a notification.  I will upgrade you to team maintainer (can manage other team members) at that time.

**Comment by dpsolomon** [comment]
ping?

**Comment by fevb** [comment]
Hi, sorry I forgot about this! I have now accepted the invitation

**Comment by dpsolomon** [comment]
Oops, just upgraded you.
