### ISSUE TITLE
Team MIT maintainer

### ISSUE THREAD

**Issue by peterkty** [amazon-picking-challenge/administration#14]
Github username: peterkty
Team MIT

Thanks

**Comment by dpsolomon** [comment]
Added to team_MIT; Invitation sent to join organization.

@peterkty update the issue when you have accepted invitation to join amazon-picking-challenge organization and I will promote you to maintainer.

**Comment by peterkty** [comment]
I've accepted the invitation. Thanks!

**Comment by dpsolomon** [comment]
Upgraded to maintainer
