### ISSUE TITLE
Team PFN maintainer

### ISSUE THREAD

**Issue by tgpfeiffer** [amazon-picking-challenge/administration#15]
Could you please make @tgpfeiffer the maintainer for team PFN? Thank you.

**Comment by dpsolomon** [comment]
I've got to set you up a repository as well. I'll let you know when it is up.

**Comment by tgpfeiffer** [comment]
Can you estimate when the repository will be set up? Thank you!

**Comment by dpsolomon** [comment]
Repo (https://github.com/amazon-picking-challenge/team_pfn) and team (https://github.com/orgs/amazon-picking-challenge/teams/team_pfn) set up. Update this ticket when you accept invitation to the organization, and I will upgrade you to team maintainer.

**Comment by tgpfeiffer** [comment]
Invitation accepted.

**Comment by dpsolomon** [comment]
All set!
