### ISSUE TITLE
New repository for returning team

### ISSUE THREAD

**Issue by zhusj** [amazon-picking-challenge/administration#16]
Dear Administrator,

I'm Shaojun Zhu with the Rutgers ARM team in the 2016 competition. As a returning team, we would like to request a new repository. I will be the maintainer and be responsible for uploading the code.

Github username: zhusj
Team name: Rutgers ARM team

Thank you,
Shaojun

**Comment by dpsolomon** [comment]
Repository created (https://github.com/amazon-picking-challenge/rutgers_arm). Team created (https://github.com/orgs/amazon-picking-challenge/teams/rutgers_arm). Update this ticket when you accept invitation and I will upgrade you to team maintainer.

**Comment by zhusj** [comment]
Hello, I have accepted the invitation. Thanks.

**Comment by dpsolomon** [comment]
All set!
