### ISSUE TITLE
Request for repository for Team IITK-TCS

### ISSUE THREAD

**Issue by sharathrjtr** [amazon-picking-challenge/administration#18]
Team maintainer github username: sharathrjtr@gmail.com from Team IITK-TCS.

**Comment by dpsolomon** [comment]
@sharathrjtr , team created at https://github.com/orgs/amazon-picking-challenge/teams/team_iitk_tcs for repository https://github.com/amazon-picking-challenge/team_iitk_tcs.
I will promote you to maintainer once you have accepted invitation.

**Comment by sharathrjtr** [comment]
@dpsolomon, sorry for the delay. I've accepted the invitation. Thanks.

**Comment by dpsolomon** [comment]
Promoted!
