### ISSUE TITLE
Repository creation request: Team Delft

### ISSUE THREAD

**Issue by mbharatheesha** [amazon-picking-challenge/administration#20]
Dear APC Organization Admin(s),

We (Team Delft) are ready to upload our code to the APC organization. As mentioned in the information page, I am requesting for a repository to be created with me as the maintainer. 

We will follow the first approach to make our code public, i.e., by cloning the new repository and copying our code into that.

Thank you!

**Comment by dpsolomon** [comment]
Great! I've set up repo https://github.com/amazon-picking-challenge/team_delft and invited you to https://github.com/orgs/amazon-picking-challenge/teams/team_delft. Once you accept the invitation, ping me and I'll promote you to maintainer. At that point, you can add other team members (including maintainers) yourself.

**Comment by mbharatheesha** [comment]
Thanks @dpsolomon! I have accepted the invitation as you might have already noticed.

**Comment by dpsolomon** [comment]
Alright, I've got you promoted. Let me know if I can do anything else to help. Happy picking!
