### ISSUE TITLE
Grant access for Team PickNik

### ISSUE THREAD

**Issue by davetcoleman** [amazon-picking-challenge/administration#21]
@gavanderhoorn requested Team PickNik share their code base but I need access  to https://github.com/amazon-picking-challenge/pick_nik to push the code. Also, could you rename the repo to have no underscore? Thanks!

**Comment by dpsolomon** [comment]
Team name and repo name updated.
Invitation sent to @davetcoleman for membership in team **[picknic](https://github.com/orgs/amazon-picking-challenge/teams/picknic)**. Will update to team maintainer once accepted.

**Comment by davetcoleman** [comment]
Thanks, code uploaded!

**Comment by dpsolomon** [comment]
Great! Happy to help.

- Maintainer status added.
