### ISSUE TITLE
Repository creation request: Team NimbRo Picking

### ISSUE THREAD

**Issue by xqms** [amazon-picking-challenge/administration#22]
Dear APC organizers,

we (Team NimbRo Picking, University of Bonn) would like to upload our code from APC 2016. Can you create a repository for us? Please use NimbRo Picking as the name (or team_nimbro_picking or similar).

Thanks!

**Comment by xqms** [comment]
*bump*

**Comment by dpsolomon** [comment]
Sorry @xqms somehow I missed this issue.

**Comment by dpsolomon** [comment]
Repository [nimbro_picking](https://github.com/amazon-picking-challenge/nimbro_picking) created, invitation sent to @amazon-picking-challenge/team_nimbro_picking . Please update this ticket after you have accepted invitation and I will elevate to team maintainer.

**Comment by xqms** [comment]
I accepted the invitation. Thanks!

**Comment by dpsolomon** [comment]
Done!
