### ISSUE TITLE
Team maintainer request

### ISSUE THREAD

**Issue by garcia-g** [amazon-picking-challenge/administration#24]
Dear ARC Organizers,

Could you please add "team-naist-panasonic" to the repo?
Username: garcia-g

Thank you and best regards,

Gustavo Garcia
Team NAIST-Panasonic

**Comment by dpsolomon** [comment]
- Added team [team_naist_panasonic](https://github.com/orgs/warehouse-picking-automation-challenges/teams/team_naist_panasonic)
- Invited @garcia-g to org/team
- Created repo [team_naist_panasonic](https://github.com/warehouse-picking-automation-challenges/team_naist_panasonic) and assigned team [team_naist_panasonic](https://github.com/orgs/warehouse-picking-automation-challenges/teams/team_naist_panasonic) with write access.

- [ ] @garcia-g : Update ticket when you have joined org
- [ ] @warehouse-picking-automation-challenges/admins : promote @garcia-g to team maintainer

**Comment by garcia-g** [comment]
Sorry for the late update.
Everything worked to upload the code.
Thanks
