### ISSUE TITLE
Team ACRV Updates

### ISSUE THREAD

**Issue by adamwtow** [amazon-picking-challenge/administration#25]
Hi, 
I'm wondering if you can create a second repo for us for our 2017 entry and call it "team_acrv_2017"
I'm also wondering if you can please change our current repo name from "team_acrv" to "team_acrv_2016".
Also I propose that the naming convention of "team_*" is applied to all existing team repos or removed from them all to keep things consistent and easier to read.
Cheers

**Comment by dpsolomon** [comment]
- Promoted @adamwtow  to team maintainer
- Created repo [team_acrv_2017](https://github.com/warehouse-picking-automation-challenges/team_acrv_2017) and assigned team @warehouse-picking-automation-challenges/team_acrv with write access.
- Updated [team_acrv](https://github.com/warehouse-picking-automation-challenges/team_acrv) to [team_acrv_2016](https://github.com/warehouse-picking-automation-challenges/team_acrv_2016)  
(**Note: you will have to update all remote references to the new address!**)
