### ISSUE TITLE
New Team Team_T2

### ISSUE THREAD

**Issue by kojiehara** [amazon-picking-challenge/administration#26]
Dear ARC Organizers,

Could you please add "Team_T2" to the repo?
 Username: kojiehara

Thank you and best regards,

Koji Ehara
 Team T2

**Comment by peterkty** [comment]
Hi Koji,

I just added a repo for Team_T2 and invited you as the admin of it.
Let me know if that works well or not. Thanks for your contribution.

Peter

**Comment by kojiehara** [comment]
Hi Peter,
It seems to be working well.  Thank you.
