### ISSUE TITLE
add team member from Team-K

### ISSUE THREAD

**Issue by k-okada** [amazon-picking-challenge/administration#4]
Hi, 

could you add @k-okada, @wkentaro to the member list?

Thanks in advance

**Comment by dpsolomon** [comment]
Can do.  Who will be team maintainer(s)?

**Comment by k-okada** [comment]
@k-okada and @wkentaro

**Comment by dpsolomon** [comment]
Great.  I just sent invitations to join the team.  As soon as they are processed I will promote both to maintainers.

**Comment by dpsolomon** [comment]
@k-okada and @wkentaro are both added to [team_k](https://github.com/orgs/amazon-picking-challenge/teams/team_k) as maintainers.  Both may add additional team members and promote maintainers.

**Comment by wkentaro** [comment]
Thanks.
