### ISSUE TITLE
[Team-K] Fork existing GitHub repository

### ISSUE THREAD

**Issue by wkentaro** [amazon-picking-challenge/administration#5]
I'm a member of Team-K. 
The project repository of us exists at https://github.com/start-jsk/jsk_picking_challenge .
Please fork it.

cc: @k-okada (Do you agree with forking?)

**Comment by dpsolomon** [comment]
@k-okada, do you agree with forking the existing repository?

**Comment by k-okada** [comment]
## Sure, please use https://github.com/start-jsk/jsk_picking_challenge/tree/0.1.0 Version, which we used in the challenge.

◉ Kei Okada

2015/09/09 22:37、Daniel Solomon notifications@github.com のメッセージ:

**Comment by dpsolomon** [comment]
Repo is forked and team_k has been added.  I cannot fork just one tag, but if you want to create a branch from tag 0.1.0, I can make that the default branch.
