### ISSUE TITLE
Request for a team 

### ISSUE THREAD

**Issue by bekris** [amazon-picking-challenge/administration#7]
Hello, 

I would like to request to be the team maintainer for the R U PRACSYS team.
User Name: "bekris"

Let me know if you need any additional piece of information.

Best,
  Kostas Bekris

**Comment by dpsolomon** [comment]
No problem Kostas, invitation posted.  Will promote to team maintainer once accepted.

**Comment by bekris** [comment]
Great, thanks!

Kostas
