### ISSUE TITLE
Request To Be A Team Maintainer

### ISSUE THREAD

**Issue by keaijiang** [amazon-picking-challenge/administration#8]
Hi,

user name: keaijiang
team name: team_nanyang

Keai Jiang

**Comment by dpsolomon** [comment]
Invitation sent. I will upgrade to team maintainer once you are registered to the team.

**Comment by dpsolomon** [comment]
Ping?
@keaijiang, you will have to accept the invitation to join team_nanyang before I can promote you to team maintainer.

**Comment by keaijiang** [comment]
Ok.

I've just accepted the invitation.
